<?xml version="1.0"?>
<!--
    Xacro file for RP-Lidar Simulator for Gazebo and RViz
    Company : Obodroid Corporation
    Author : Theppasith N. <theppasith@gmail.com>
-->
<robot name="rp-lidar" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Lidar Sensors Model -->
    <link name="lidar_link">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="${lidar_size} ${lidar_size} ${lidar_size}" />
        </geometry>
        <material name="Blue" />
    </visual>
    </link>

    <joint name="lidar_joint" type="fixed">
        <origin xyz="${base_link_to_lidar_x}
          ${base_link_to_lidar_y}
          ${base_link_to_lidar_z + optical_z_offset + metal_sheet_thickness}"
          rpy="0 0 0" />
        <parent link="base_link" />
        <child link="lidar_link" />
    </joint>

    <gazebo reference="lidar_link">
        <material>Gazebo/Blue</material>
        <turnGravityOff>false</turnGravityOff>
        <sensor type="ray" name="lidar_sensor">
            <pose>${lidar_size/2} 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>5.5</update_rate>
            <!-- update rate 40 -->
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <!-- samples 360 -->
                        <resolution>1</resolution>
                        <min_angle>-2</min_angle>
                        <max_angle>2</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.10</min>
                    <max>6</max>
                    <resolution>0.001</resolution>
                </range>
                <noise>
                  <type>gaussian</type>
                  <mean>0.01</mean>
                  <stddev>0.015</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>lidar_link</frameName>
            </plugin>
        </sensor>
    </gazebo>
</robot>
