<?xml version="1.0"?>
<!--
    Constants to use with Xacro file for SOM_O_ROBOT (20CM width)
    Company : Obodroid Corporation
    Author : Theppasith N. <theppasith@gmail.com>
-->
<robot name="som_o_robot_25cm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Constants (m-kg-s-radians unit system) -->
    <xacro:property name="M_PI" value="3.1415926535897931"/>
    <xacro:property name="M_PI_2" value="1.570796327"/>
    <xacro:property name="DEG_TO_RAD" value="0.017453293"/>

    <!-- Meterials properties -->
    <xacro:property name="metal_sheet_thickness" value="0.003"/>

    <!-- Base Link Constants -->
    <!-- Inertial components , Mass (kgs) -->
    <xacro:property name="base_mass" value="0.2"/>
    <xacro:property name="base_radius" value="0.25"/>
    <xacro:property name="base_height" value="0.22"/>
    <xacro:property name="base_link_visual_mesh_offset_z" value="0.55"/>

    <!-- Chassis Collsion -->
    <xacro:property name="base_col_box_height" value="0.183091"/>
    <xacro:property name="base_col_box_length" value="0.200"/>
    <xacro:property name="base_col_box_width" value="0.180"/>

    <!-- Wheels -->
    <xacro:property name="wheel_radius" value="0.042" />
    <xacro:property name="wheel_height" value="0.024" />
    <xacro:property name="wheel_mass" value="2.5" /> <!-- in kg-->
    <xacro:property name="gap_to_wheel" value="0.017" />
    <xacro:property name="base_x_origin_to_wheel_origin" value="0" />
    <!-- <xacro:property name="base_y_origin_to_wheel_origin" value="0.092" /> -->
    <xacro:property name="base_y_origin_to_wheel_origin" value="${base_col_box_width/2 +gap_to_wheel}" />
    <xacro:property name="base_z_origin_to_wheel_origin" value="0.00" />

    <!-- Lidar Specs -->
    <xacro:property name="lidar_size" value="0.005" />
    <xacro:property name="base_link_to_lidar_x" value="0.07" />
    <xacro:property name="base_link_to_lidar_y" value="0.000" />
    <xacro:property name="base_link_to_lidar_z" value="0.183091" />
    <xacro:property name="optical_z_offset" value="0.03080" />

    <!-- Macro for calculating inertia of cylinder -->
    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
          iyy="${m*(3*r*r+h*h)/12}" iyz="0" izz="${m*r*r/2}"/>
    </xacro:macro>

</robot>
