<?xml version="1.0"?>
<robot name="kamtoa_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Hokuyo Sensors Model -->
    <link name="camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${cameraSize} ${cameraSize} ${8*cameraSize}"/>
            </geometry>
            <material name="Red"/>
        </visual>
    </link>

    <joint name="camera_joint" type="fixed">
        <origin xyz="${- base_radius + cameraSize/2} 0 ${base_height+4*cameraSize}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="camera_link"/>
    </joint>

    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>
        <turnGravityOff>false</turnGravityOff>
        <sensor type="camera" name="camera1">
            <update_rate>30.0</update_rate>
            <camera name="head">
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>800</width>
                    <height>800</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.02</near>
                    <far>300</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>kamtoa/camera_rgb</cameraName>
                <imageTopicName>kamtoa/camera/rgb</imageTopicName>
                <cameraInfoTopicName>kamtoa/camera/camera_info</cameraInfoTopicName>
                <frameName>camera_link</frameName>
                <hackBaseline>0.07</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
            </plugin>
        </sensor>
    </gazebo>
</robot>
