<?xml version="1.0"?>

<robot name="kamtoa_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Wheel file -->
    <xacro:include filename="$(find kamtoa_description)/urdf/wheel.urdf.xacro" />
    <xacro:include filename="$(find kamtoa_description)/urdf/constant.xacro" />
    <xacro:include filename="$(find kamtoa_description)/urdf/material.xacro" />
    <xacro:include filename="$(find kamtoa_description)/urdf/hokuyo.xacro" />
    <xacro:include filename="$(find kamtoa_description)/urdf/diff_drive_plugin.xacro" />

    <!-- Base_Footprint (ground mark)  -->
    <link name="base_footprint">
    <inertial>
        <mass value="0.0001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
    </inertial>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius - base_z_origin_to_wheel_origin}" rpy="0 0 0" />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>

    <gazebo reference="base_footprint">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <!-- Base_Link (Action body/chassis of the robot) -->
    <link name="base_link">
    <inertial>
        <mass value="${base_mass}" />
        <origin xyz="0 0 0" />
        <!--The 3x3 rotational inertia matrix. -->
        <cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}" />
    </inertial>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <cylinder length="${base_height}" radius="${base_radius}" />
        </geometry>
        <material name="White" />
    </visual>

    <collision>
        <origin xyz="0 0 0" rpy="0 0 0 " />
        <geometry>
            <cylinder length="${base_height}" radius="${base_radius}" />
        </geometry>
    </collision>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/White</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <!-- Front Caster wheel  -->
    <link name="caster_front_link">
    <visual>
        <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
        <geometry>
            <sphere radius="${caster_f_radius}" />
        </geometry>
        <material name="Black" />
    </visual>

    <collision>
        <geometry>
            <sphere radius="${caster_f_radius}" />
        </geometry>
        <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
    </collision>
    <inertial>
        <mass value="${caster_f_mass}" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
    </link>

    <joint name="caster_front_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_front_link" />
        <origin xyz="0.115 0.0 0.007" rpy="${-M_PI/2} 0 0" />
    </joint>

    <gazebo reference="caster_front_link">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <!-- Back Caster wheel  -->
    <link name="caster_back_link">
    <visual>
        <origin xyz="0.02 0.02 0 " rpy="${M_PI/2} 0 0" />
        <geometry>
            <sphere radius="${caster_b_radius}" />
        </geometry>
        <material name="Black" />
    </visual>

    <collision>
        <geometry>
            <sphere radius="${caster_b_radius}" />
        </geometry>
        <origin xyz="0 0.02 0 " rpy="${M_PI/2} 0 0" />
    </collision>
    <inertial>
        <mass value="${caster_b_mass}" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
    </link>

    <joint name="caster_back_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_back_link" />
        <origin xyz="-0.135 0.0 0.009" rpy="${-M_PI/2} 0 0" />
    </joint>

    <gazebo reference="caster_back_link">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <!-- Wheel -->
    <wheel fb="front" lr="right" parent="base_link" translateX="0" translateY="0.5" flipY="1" />
    <wheel fb="front" lr="left" parent="base_link" translateX="0" translateY="-0.5" flipY="1" />
</robot>
