<?xml version="1.0"?>

<robot name="som_o_robot_30cm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Base_Link (Action body/chassis of the robot) -->
  <link name="base_link">
  <inertial>
      <mass value="${base_mass}" />
      <origin xyz="0 0 0" />
      <!--The 3x3 rotational inertia matrix. -->
      <cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}" />
  </inertial>

  <!-- Base_Link Visual (mesh from STL) -->
  <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
          <mesh filename="package://som_o_description/meshes/obodroid1.stl"/>
      </geometry>
      <material name="White" />
  </visual>

  <!-- Base_Link Collision Model -->
  <collision>
      <origin xyz="0 0 ${base_col_box_height/2}" rpy="0 0 0 " />
      <geometry>
          <box size="${base_col_box_length} ${base_col_box_width} ${base_col_box_height}" />
      </geometry>
  </collision>
  </link>

  <!--  -->
  <gazebo reference="base_link">
      <material>Gazebo/White</material>
      <turnGravityOff>false</turnGravityOff>
  </gazebo>



</robot>
