scan_filter_chain:
- name: angular_bounds
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle: -3.2
    upper_angle: -1.8
- name: angular_bounds2
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle: 1.8
    upper_angle: 3.2
